### ISSUE TITLE
如何将它用在gulp之上配合postcss使用？

### ISSUE THREAD

**Issue by iuunhao** [cupools/img-sprite#1]
如何将它用在gulp之上配合postcss使用？

**Comment by cupools** [comment]
`glup` 和 `postcss` 都是单文件编译流程。`img-sprite` 在编译之前需要拿到所有的样式文件，然后在一个节点统一处理得到精灵图片，之后再更新样式文件，因此可能不适合用在类似的单文件编译流程里面。如果真要用进去的话，是不是可以考虑在 `postcss` 处理输出全部的临时样式文件之后，由 `glup` 创建任务调用 `img-sprite` 去统一处理，有点拙的样子。
